---
title: "dataPrep"
author: "Clint McKenna"
date: "07/05/2023"
output: html_document
---


# data prep
```{r}

# load packages
library(tidyverse)

# custom functions
## dplyr select
select <- dplyr::select

## convert all cols to character
toChar <- function(df){
  df %>% mutate_all(as.character)
}

# prolific files


# read in data
dat <- read_csv('../data/all_apps_wide-2024-06-25.csv') 


dat <- dat %>%
  mutate(workerId = participant.label) %>%
  filter(!is.na(workerId)) %>%
  filter(participant._current_page_name == 'debrief')


# in case some duplicates, take only the first record
dat <- dat %>%
  distinct(workerId, .keep_all= TRUE)




# subject var
dat <- dat %>%
  mutate(subject = 1:n())

# remove clutter


```

# text data
```{r}

txtList <- list()

n <- as.numeric(nrow(dat))

txt <- dat %>%
    select(workerId, subject, 
           botMsg = discomfortBot.1.player.msg,
           humanMsg = discomfort.1.player.msg)
  


for (i in 1:n) {
    
  currentRow <- txt[i,]
  
  currentBot <- fromJSON(currentRow$botMsg)[,'content'] %>%
    enframe() %>%
    unnest(value) %>%
    transmute(workerId = currentRow$workerId,
              subject = currentRow$subject,
              botNum = name,
              botText = value)
  
    
    currentHuman <- fromJSON(currentRow$humanMsg)[,'content'] %>%
      enframe() %>%
      unnest(value) %>%
      transmute(workerId = currentRow$workerId,
                subject = currentRow$subject,
                humanNum = name,
                humanText = value)
    
    
}


```



# feeling thermometer
```{r}

FT <- dat %>%
  select(subject, contains('FT_'), discomfortBot.1.player.selfParty, discomfortBot.1.player.botParty,
         discomfort.1.player.partnerParty) %>%
  transmute(subject = subject,
            party = discomfortBot.1.player.selfParty,
            botParty = discomfortBot.1.player.botParty,
            partnerParty = discomfort.1.player.partnerParty,
            FT0 = discomfortBot.1.player.FT_rep0 - discomfortBot.1.player.FT_dem0,
            FT1 = discomfort.1.player.FT_rep1 - discomfort.1.player.FT_dem1,
            FT2 = discomfort.1.player.FT_rep2 - discomfort.1.player.FT_dem2)
            # FT0 = discomfortBot.1.player.FT_gun0,
            # FT1 = discomfort.1.player.FT_gun1,
            # FT2 = discomfort.1.player.FT_gun2)


FT <- FT %>%
  mutate(botType = case_when(
    party == 'Democrat' & botParty == 'Democrat' ~ 'congenial bot',
    party == 'Democrat' & botParty == 'Republican' ~ 'uncongenial bot',
    party == 'Republican' & botParty == 'Republican' ~ 'congenial bot',
    party == 'Republican' & botParty == 'Democrat' ~ 'uncongenial bot',
    TRUE ~ NA_character_)) %>%
  mutate(humanType = case_when(
    party == 'Democrat' & partnerParty == 'Democrat' ~ 'congenial human',
    party == 'Democrat' & partnerParty == 'Republican' ~ 'uncongenial human',
    party == 'Republican' & partnerParty == 'Republican' ~ 'congenial human',
    party == 'Republican' & partnerParty == 'Democrat' ~ 'uncongenial human',
    TRUE ~ NA_character_))
  
    
  
tmp <- FT %>%
  filter(party == 'Democrat' | party == 'Republican') %>%
  group_by(party, botType, humanType) %>%
  summarise(m0 = mean(FT0, na.rm = TRUE),
            m1 = mean(FT1, na.rm = TRUE),
            m2 = mean(FT2, na.rm = TRUE),
            n = n()) %>%
  na.omit()

tmp <- tmp %>%
  pivot_longer(
    cols = starts_with('m'),
    names_to = 'time',
    values_to = 'rating')





```



```{r}



tmp %>%
  na.omit() %>%
  mutate(time = as.numeric(gsub('m', '', time))) %>%
  ggplot(., aes(x = time, y = rating, group = party, color= fct_rev(party))) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~ botType + humanType)


```
